### ISSUE TITLE
Extension flags not working?

### ISSUE THREAD

**Issue by lhagan** [benmills/robotskirt#12]
I feel like I must be missing something, but I can't seem to get the extension flags to work. I'm using robotskirt from GitHub (the version on npm is not up to date) and successfully compiled it.

This snippet (pretty much the example from the readme) does not autolink; it just returns `<p>Wow, this becomes http://autolink.ed !</p>`

```
var rs = require('robotskirt'),
    fs = require('fs'),
    sys = require('util');

var renderer = new rs.HtmlRenderer(),
    flags = rs.EXT_FENCED_CODE & rs.EXT_AUTOLINK & rs.EXT_TABLES;

rs.markdown(renderer, 'Wow, this becomes http://autolink.ed !', function (html) {
  sys.puts(html);
}, flags);
```

I tried tables as well with no more luck.

**Comment by benmills** [comment]
Thanks for letting me know. We just added flags with the last few commits and are trying to work out a few issues before we publish it to npm. I'll take a look at this as soon as I can.

**Comment by mildsunrise** [comment]
Mea culpa.
To combine the bits of the extensions,
I should have used `|` instead of `&` (which does the opposite!)

``` javascript
EXT1 | EXT2
// or also:
EXT1 + EXT2
```

**Warning!** The latter will work _only_ if the extensions
don't have any common bits. It's better to use `|`.
