### ISSUE TITLE
NPM package for version 1.0.0?

### ISSUE THREAD

**Issue by BinaryMuse** [benmills/robotskirt#14]
Hey,

I noticed in c1d377d5dc7a9c55d5570fee6bd85148686269a2 that you updated the package to report version 1.0.0, and I was wondering if you had plans to publish this to NPM soon (currently NPM still has version 0.2.5).

Thanks!

**Comment by benmills** [comment]
I'm working on a few issues I currently have with the API before I actually publish the 1.0.0 version.

**Comment by mildsunrise** [comment]
**Well, version 2 is now published!**
Checkout #21 and leave any feedback there.
