### ISSUE TITLE
OL following a UL fails

### ISSUE THREAD

**Issue by zzen** [benmills/robotskirt#15]
The following markdown

``` markdown
- a
- b
- c

1. one
2. two
3. three
```

compiles here on Github correctly to:
- a
- b
- c
1. one
2. two
3. three

But in Robotskirt it compiles to 6 items of an unordered list. This is a bug frequent in many Markdown implementations but not present in GFM (which also uses Sundown). So my guess is a newer version of the sundown submodule would probably fix this.

Any chance this could get updated?

**Comment by zzen** [comment]
Update: the latest [redcarpet](https://github.com/tanoku/redcarpet) indeed does not suffer this problem (using a 3month old tanoku/sundown@8e5b0d1)

**Comment by benmills** [comment]
We're working on upgrading the version of sundown we use right now. I'll leave this issue open and close it once we push the new version.

**Comment by mildsunrise** [comment]
Related issue: #16
See also [these comments](https://github.com/benmills/robotskirt/pull/11#issuecomment-6360801).

**Comment by mildsunrise** [comment]
You're right, this is doesn't happen on the [unstable branch](https://github.com/benmills/robotskirt/tree/unstable) of Robotskirt.
With the example `parser.js` program:

<pre>
<b>$ bin/parser.js</b>
- a
- b
- c

1. one
2. two
3. three
<em>&lt;press Ctrl-D></em>
</pre>


and the output is as expected:

``` html
<ul>
<li>a</li>
<li>b</li>
<li>c</li>
</ul>

<ol>
<li>one</li>
<li>two</li>
<li>three</li>
</ol>
```

**Comment by zzen** [comment]
Yeah, i expected that, that's great.

Any ETA on when `unstable` will become `stable`? I won't sue you if you get it wrong, but just give me an idea…

**Comment by mildsunrise** [comment]
It's now in `beta`!
And **_really**_ fast:

<pre>Current:         <b>1795ms</b>
Unstable (beta): <b>1350ms</b>  -420ms (&darr;24%)</pre>

**Comment by mildsunrise** [comment]
@zzen v2 of Robotskirt is now `stable` and already published!
See #21 and [the NPM registry](https://npmjs.org/package/robotskirt).

I'm closing this, keep posting any bugs you found.
Also be sure to leave any feedback at #21. Thanks!
