### ISSUE TITLE
Update sundown to recent version

### ISSUE THREAD

**Issue by przemoc** [benmills/robotskirt#16]
Over the year sundown had many improvements and bug fixes. Thus it would be good to update sundown submodule in robotskirt repo.

**Comment by mildsunrise** [comment]
Yeah, we're looking into it. See [this thread](https://github.com/benmills/robotskirt/pull/11#issuecomment-6360801).
Anyway, keep in mind that there are new features,
and it's not just update.

**Comment by przemoc** [comment]
Sure, thanks for the link. I haven't noticed that there was previous update-related discussion.

I think that sundown upgrade procedure alone deserves it's own ticket, but if you think otherwise feel free to close it.

**Comment by mildsunrise** [comment]
No, you're right, it deserves. :)

**Comment by przemoc** [comment]
BTW I've created the [issue 46](https://github.com/flatiron/blacksmith/issues/46) at [blacksmith](https://github.com/flatiron/blacksmith) (a static site generator built with Node.js, JSDOM, and Weld) about switching it from [marked](https://github.com/chjj/marked) to Robotskirt.

**Comment by mildsunrise** [comment]
@benmills @przemoc
I've already created an [unstable](https://github.com/benmills/robotskirt/tree/unstable) branch,
and updated the submodule to the last commit.

Previous commit: 5d201dbcdc291adfa9c2dc4f8ddb2ff1fe6202a9
Current commit: c744346e507e7f905d4b401de78db4404068a43c
**You can [see the diff and commits here](https://github.com/tanoku/sundown/compare/5d201dbcdc291adfa9c2dc4f8ddb2ff1fe6202a9...c744346e507e7f905d4b401de78db4404068a43c).**

**Comment by mildsunrise** [comment]
Now Sundown is at his very latest version,
and Robotskirt is at all his glory wih the flaming v2.
Now, you can do:

``` javascript
var rs = require('robotskirt');
console.log(rs.versions.sundown);
```

To see the version of the bundled Sundown.

**Comment by mildsunrise** [comment]
I'm closing the issue, feel free to reopen it in the future.
