### ISSUE TITLE
Question: AST from Markdown

### ISSUE THREAD

**Issue by zzen** [benmills/robotskirt#18]
This is more akin a quick question/feasibility - I need to get parsed AST tree out of robotskirt (and write my own renderer). Is there a guide/how-to/API for that?

**Comment by mildsunrise** [comment]
Support for custom renderers is really _haaard_ to implement,
but it seems we are finally getting it working.

Soon it'll be fully stable (for now there's only one function to customize)
but if you're impatient, keep an eye on the [unstable](https://github.com/benmills/robotskirt/commits/unstable) branch
and the [wiki page](https://github.com/benmills/robotskirt/wiki/Introducing-function-wrapping) of that feature.

**Comment by mildsunrise** [comment]
With v2, there's (finally) **full support for custom renderers!**
The [new readme](https://github.com/benmills/robotskirt/tree/unstable#readme) (to be published soon) explains how to use them.
There's also an example of [an ANSI renderer](https://github.com/benmills/robotskirt/blob/master/examples/ansi-rend.js) bundled with Robotskirt.

I'm not closing this issue.
If you have trouble with custom renderers in Robotskirt,
please post them here. Also feel free to leave any other feedback at #21.

**Comment by mildsunrise** [comment]
@zzen Which format should be the parsed AST tree?
JSON? XML? YAML?

**Comment by zzen** [comment]
Well, since the interface is in Javascript, and I will consume the AST tree in Javascript, I would certainly prefer getting just a plain Javascript object.

However if you must serialize it into a string, then JSON would be my choice.

**Comment by mildsunrise** [comment]
OK, I'll try to make something these days.
Meanwhile, I'm closing the issue, because this isn't related
to a bug or feature request in Robotskirt.
