### ISSUE TITLE
question: is toHtmlSync slow?

### ISSUE THREAD

**Issue by guileen** [benmills/robotskirt#2]
My thought, if incorrect, point it out

toHtmlSync has the same performance with toHtml. toHtml or toHtmlSync depends on case, if we write a `function parseFile(file, cb)` we should use toHtml, if we use in template which only allow sync call, we should use `toHtmlSync`

**Comment by benmills** [comment]
Hey guileen,

I'm not sure I understand your question. Are you asking when it would be better to use toHtmlSync vs toHtml? The speed should be the same for how long it takes robotskirt to parse the markdown. However toHtml is non-blocking, so it won't stop the rest of your application while it is parsing.

Let me know what else I can do to help.

**Comment by guileen** [comment]
my English is not very good, i will try my best to explain my question.
- yes, i am adking when to use tohtmlsync.
- parse is not a IO operation, so how could it wont stop the rest of code when it parsing?

**Comment by benmills** [comment]
From what I understand the code won't move forward till the parsing is complete. So take this for example:

``` javascript
var html = markdown.toHtmlSync("# test");
// Do something else
```

This couldn't won't do something else until robotskirt has parsed the markdown. However if we switch to `toHtml`:

``` javascript
markdown.toHtml("# test", function(html){
  // Do something with the parsed html
});
// Do something else
```

We will immediately be able to do something else and when robotskirt is done parsing we can do what ever we passed into the callback with the parsed html. 

However I'm definitely not a master at node or evented programming so maybe this is the wrong approach to take for this.
