### ISSUE TITLE
Docs for Extensions

### ISSUE THREAD

**Issue by semperos** [benmills/robotskirt#27]
Is there documentation for how your particular extensions work? I'm personally not a C guru, and it'd be nice to see a table of your extensions and the syntax they add to Markdown.

If I'm missing this, I apologize, and would welcome a link to the appropriate documentation.

**Comment by mildsunrise** [comment]
Hi,

no, you're right, there's no documentation on extensions yet.
On the other hand, keep in mind that this is just a wrapper;
the actual processing is done at the native library, [Sundown](https://github.com/vmg/sundown),
so you should look there also.

You can find better documentation about the list of extensions
at Redcarpet, the official Sundown bindings to Ruby. Copied from [there](https://github.com/vmg/redcarpet#and-its-like-really-simple-to-use):

```
extensions - a hash containing the Markdown extensions which the parser
            will identify. The following extensions are accepted:

            :no_intra_emphasis - do not parse emphasis inside of words.
                Strings such as `foo_bar_baz` will not generate `<em>`
                tags.

            :tables - parse tables, PHP-Markdown style

            :fenced_code_blocks - parse fenced code blocks, PHP-Markdown
                style. Blocks delimited with 3 or more `~` or backticks
                will be considered as code, without the need to be
                indented. An optional language name may be added at the
                end of the opening fence for the code block

            :autolink - parse links even when they are not enclosed in
                `<>` characters. Autolinks for the http, https and ftp
                protocols will be automatically detected. Email addresses
                are also handled, and http links without protocol, but
                starting with `www.`

            :strikethrough - parse strikethrough, PHP-Markdown style
                Two `~` characters mark the start of a strikethrough,
                e.g. `this is ~~good~~ bad`

            :lax_spacing - HTML blocks do not require to be surrounded
                by an empty line as in the Markdown standard.

            :space_after_headers - A space is always required between the
                hash at the beginning of a header and its name, e.g.
                `#this is my header` would not be a valid header.

            :superscript - parse superscripts after the `^` character;
                contiguous superscripts are nested together, and complex
                values can be enclosed in parenthesis,
                e.g. `this is the 2^(nd) time`
```

**Comment by mildsunrise** [comment]
However, Sundown is now deprecated/freezed (see vmg/sundown@37728fb2d7137), because
a new next-generation standard & parser will be released soon:

> [...] Sundown is currently frozen as we're working with the Reddit, StackOverflow and Meteor developers to design a formal Markdown standard and parser that will supersede Sundown in all these websites (and in GitHub, of course).

**Comment by semperos** [comment]
Thanks, appreciate the info.
