### ISSUE TITLE
can not use in expressjs

### ISSUE THREAD

**Issue by guileen** [benmills/robotskirt#3]
```
app.get('/', function(req, res, next){
  res.render('index', {markdown: require('robotskirt')})
});
```

index.jade

``````
!= markdown.toHtmlSync('```javascript\nfor(var i =  0;i<10;i++){}\n```')
``````

when I refresh the page, sometimes I got garbled text.

**Comment by benmills** [comment]
I'm looking into this now, let me know if you find anything else out.

**Comment by benmills** [comment]
What I'm seeing now is randomly an extra character is added to the bottom or it doesn't return anything at all. Is that what you are seeing as well? 

Could you give me the version of node and express you are using?

**Comment by guileen** [comment]
sometimes some extra, sometimes worst. i am now on a phone can't give details version, but node is  0.5-pre, express is 2.x

**Comment by guileen** [comment]
how is it going?

**Comment by benmills** [comment]
I've been talking with some people in the #node.js irc channel and I think it might be related to garbage collection. Hopefully soon I'll be be able test this and force GC to happen to see if that is related.

**Comment by guileen** [comment]
thank you for your hard work. this will be the best markdown parser for
nodejs.

**Comment by benmills** [comment]
I've spent some more time on this and I think I have at least one of the issues solve. I was adding an extra byte to the input string before I parsed it and I think that was causing extra characters to be added at the end of the HTML.

I'm still seeing it return nothing in express every once and a while. I'm not 100% on why this is happening I'm still testing with the garbage collection theory, but I'm not sold that GC is causing this. I'm going to hopefully test using some other frame works and see if its limited to just express or if the bug happens in other cases as well.

Thanks for the kind words, I'm glad you like the lib!

**Comment by benmills** [comment]
Version 0.2.1 should fix both issues now. Let me know if you run into any other problems!

**Comment by guileen** [comment]
Wow, greate.

**Comment by guileen** [comment]
when I 'npm install robotskirt' I got 

`OSError: [Errno 2] No such file or directory: '/Users/benmills/code/robotskirt/build'`

**Comment by benmills** [comment]
Did you already have it installed? Or is this a fresh install? Also what version on npm do you have?

**Comment by guileen** [comment]
I installed it before, but I uninstalled for this issue, now is a reinstall.

npm version is 1.0.1-rc9

**Comment by benmills** [comment]
I know I had some other issues with installing anything using npm 1.0.1-rc, do you think you could try with npm 1.0.6 (the current version). Or you could try to install other packages like express to see if the issue is only robotskirt.

**Comment by guileen** [comment]
resolved after I upgrade my npm.

**Comment by benmills** [comment]
Great. I also pushed a few changes that might have also fixed this. Let me know if anything else comes up.
