### ISSUE TITLE
Footnotes aren't supported

### ISSUE THREAD

**Issue by silvenon** [benmills/robotskirt#33]

**Comment by mildsunrise** [comment]
That's because Robotskirt is based on Sundown, and Sundown
doesn't parse footnotes.

But the successor to Sundown, Hoedown, will soon reach
version 3. Among other things, it can parse footnotes.
So stay tuned...

2014-03-24 22:09 GMT+01:00 Matija Marohnić notifications@github.com:

**Comment by silvenon** [comment]
Oh, I guess this can be closed then. Thanks :smile:

**Comment by mildsunrise** [comment]
@silvenon It's finally out. [node-hoedown](https://github.com/hoedown/node-hoedown) is in beta, with complete docs and examples. To get it:

```
npm install hoedown
```

It brings all the improvements in Hoedown (faster, more features, cleanup, can render more than 15MB, etc.), plus all its utilities. It's been made a lot simpler to use, but there are no custom renderers.

Please, try it out! :) I need some feedback before it's ready for production.

**Comment by silvenon** [comment]
Ok, will do :)
