### ISSUE TITLE
what is the license for this code?

### ISSUE THREAD

**Issue by trentm** [benmills/robotskirt#5]
thanks!

**Comment by benmills** [comment]
MIT, sorry about not including it before. It's in the readme for now.

**Comment by trentm** [comment]
Thanks!

On Wed, Jun 22, 2011 at 4:08 PM, benmills
reply@reply.github.com
wrote:

> MIT, sorry about not including it before. It's in the readme for now.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/benmills/robotskirt/issues/5#issuecomment-1421862

## 

Trent Mick
