### ISSUE TITLE
Problem with toHtmlSync()

### ISSUE THREAD

**Issue by rafeca** [benmills/robotskirt#9]
When I call sequentially several times the method `toHtmlSync()`, sometimes I get unexpected results.

As a proof, the following script:

``` js
var output;
for (var i=0;i<1000;i++) {
  output = markdown.toHtmlSync('*sync!*').toString();

  if (output !== '<p><em>sync!</em></p>\n') {
    console.log('Fails!');
  }
}
```

Will print 'Fails' several times.

When I parse more complicated strings (for example full files), I got unexpected results almost always:

``` js
var output = {};
['README.md', 'History.md', 'Authors.md'].forEach(function(file) {
  output[file] = markdown.toHtmlSync(
    fs.readFileSync(path.join(options.currentPath, file), 'utf8')
  ).toString();
}
```

I'm currently using Node.js 0.6.4 and robotskirt 0.2.4 under OSX

**Comment by benmills** [comment]
Thanks for letting me know about this. I ran into this issue when I was initially worked on this project for node 0.4. I take a look at this as soon as possible.

**Comment by benmills** [comment]
Did you test this with toHtml out of curiosity?

**Comment by rafeca** [comment]
Yes, I tested it and I couldn't reproduce the issue

**Comment by benmills** [comment]
Commit 6dfc986484ec1bc13f3cc3f15ce0221b571043c1 should fix this.

**Comment by rafeca** [comment]
awesome! I can confirm that it works like a charm

**Comment by rafeca** [comment]
Hi, can you make a new release of the package with this fix please?

**Comment by benmills** [comment]
I'll publish a package as soon as I can, thanks for letting me know.

On Sun, Jan 22, 2012 at 1:39 PM, Rafael de Oleza <
reply@reply.github.com

**Comment by benmills** [comment]
Version 0.2.5 has just been published: http://search.npmjs.org/#/robotskirt

**Comment by rafeca** [comment]
Thanks!
